# Generated by Django 4.2.7 on 2023-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_data_end_year_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
