# Generated by Django 4.2.7 on 2023-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_data_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.CharField(max_length=50),
        ),
    ]
