# Generated by Django 4.2.7 on 2023-11-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_intencity_data_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_id', to='main.country'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pestle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pestle_id', to='main.pestle'),
        ),
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_id', to='main.region'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_id', to='main.sector'),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_id', to='main.source'),
        ),
        migrations.AlterField(
            model_name='data',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_id', to='main.topic'),
        ),
    ]
